config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing_pages#home'
  get 'home', to: 'landing_pages#home'
  get 'about_us', to: 'landing_pages#about_us'
  get 'celebrities', to: 'celebrities#index'
  get 'celebrities/new', to: 'celebrities#new'
  get 'celebrities/:id', to: 'celebrities#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/celebrity.rb
class Celebrity < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/celebrities_controller.rb
class CelebritiesController < ApplicationController
	def index
		@celebrities = Celebrity.all
	end
	def show
		puts "we are in the show action"
		puts "the params are #{params.inspect}"
		puts "#{params['id']}"
		@celebrity = Celebrity.where('name' => params['id']).take
		puts "the celebrity is #{@celebrity.inspect}"
	end
	def new
		@celebrity = Celebrity.new
	end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
	def home
	end
	def about_us
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/celebrities_helper.rb
module CelebritiesHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/views/celebrities/index.html.erb
yay celebrities!
<div class='container'>
<ul class="list-group">
	<% @celebrities.each do |c| %>
		<li class="list-group-item"><%= c.name %></li>
	<% end %>
</ul>
</div>

app/views/celebrities/new.html.erb
blah

<%= simple_form_for @celebrity do |f| %>
  <%= f.input :name %>
  <%= f.input :celebrity_rating %>
  <%= f.input :category %>
  <%= f.button :submit %>
<% end %>

app/views/celebrities/show.html.erb
<%= @celebrity.name %>, <%= @celebrity.celebrity_rating %>, <%= @celebrity.category %>

app/views/landing_pages/about_us.html.erb
blah blah

hit <%= link_to 'take me to the home page', root_path %> to get to our home page

app/views/landing_pages/home.html.erb
 blah

 hit <%= link_to 'take me to the about page', about_us_path %> to get to our about us page!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrapRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Brand</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">One more separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	      <form class="navbar-form navbar-left">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
  	<div class='container'>
    	<%= yield %>
    </div>
  </body>
</html>